version: '3'

services:
  eureka:
    image: anapsix/alpine-java:8_jdk_unlimited
    ports:
      - '8761:8761'
    working_dir: /app
    volumes:
      - ./eureka-server:/app
    command: './gradlew bootRun'
    environment:
      - GRADLE_USER_HOME=cache
      - SPRING_PROFILES_ACTIVE=dev
  api-gateway:
    image: anapsix/alpine-java:8_jdk_unlimited
    ports:
      - '8080:8080'
    working_dir: /app
    volumes:
      - ./api-gateway:/app
    depends_on:
      - eureka
    command: './gradlew bootRun'
    environment:
      - GRADLE_USER_HOME=cache
      - SPRING_PROFILES_ACTIVE=dev
#  developer-salary-api:
#    image: anapsix/alpine-java:8_jdk_unlimited
#    ports:
#      - '8081:8081'
#    working_dir: /app
#    volumes:
#      - ./developer-salary-api:/app
#    depends_on:
#      - eureka
#    command: './gradlew bootRun'
#    environment:
#      - GRADLE_USER_HOME=cache
#      - SPRING_PROFILES_ACTIVE=dev
  bootcamps-api:
    image: anapsix/alpine-java:8_jdk_unlimited
    ports:
      - '8082:8082'
    working_dir: /app
    volumes:
      - ./bootcamps-api:/app
    depends_on:
      - eureka
    command: './gradlew bootRun'
    environment:
      - GRADLE_USER_HOME=cache
      - SPRING_PROFILES_ACTIVE=dev
  salary-api:
      image: anapsix/alpine-java:8_jdk_unlimited
      ports:
        - '8083:8083'
      working_dir: /app
      volumes:
        - ./salary-api:/app
      depends_on:
        - eureka
      command: './gradlew bootRun'
      environment:
        - GRADLE_USER_HOME=cache
        - SPRING_PROFILES_ACTIVE=dev
#  client:
#      image: node:latest
#      build: ./client
#      ports:
#        - 3000:3000
#      working_dir: /dashboard
#      volumes:
#        - ./client:/client
#      command: 'yarn start'
#      depends_on:
#        - eureka
#        - postgresdev
#        - bootcamps-api
#        - salary-api
  postgresdev:
      image: postgres
      ports:
        - "5432:5432"
      environment:
        - POSTGRES_PASSWORD=password
        - POSTGRES_USER=postgres
        - POSTGRES_DB=pgdev